import numpy as np

np.random.seed(42)
np.set_printoptions(suppress=True, precision=2)

# Load the data generated by 01.generatedata.py instead of
# regenerating it here
data = np.loadtxt("data/crash_data.csv", delimiter=",", skiprows=1)

X = data[:, :4]  # traffic_volume, average_speed, rain, night
y = data[:, 4]   # crash

N = len(y)

# Shuffle indices
indices = np.arange(N)
np.random.shuffle(indices)

# 80% train, 20% test
split_index = int(0.8 * N)

train_indices = indices[:split_index]
test_indices = indices[split_index:]

X_train = X[train_indices]
y_train = y[train_indices]

X_test = X[test_indices]
y_test = y[test_indices]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

print("\nTraining crash percentage:")
print(np.mean(y_train) * 100)

print("\nTesting crash percentage:")
print(np.mean(y_test) * 100)

# -------------------------
# Save the split so downstream
# scripts don't regenerate/reshuffle it
# -------------------------

train_data = np.column_stack((X_train, y_train))
test_data = np.column_stack((X_test, y_test))

header = "traffic_volume,average_speed,rain,night,crash"

np.savetxt("data/train.csv", train_data, delimiter=",", header=header, comments="", fmt="%.6f")
np.savetxt("data/test.csv", test_data, delimiter=",", header=header, comments="", fmt="%.6f")

print("\nSaved data/train.csv:", train_data.shape)
print("Saved data/test.csv:", test_data.shape)
